/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DistribuidoraPetroPeru;

/**
 *
 * @author HP
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuPrecios = new javax.swing.JMenu();
        jMenuCarrito = new javax.swing.JMenu();
        jMenuFacturas = new javax.swing.JMenu();
        jMenuEstado = new javax.swing.JMenu();
        jMenuCompra = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido a nuestro Portal de Ventas");

        jMenuPrecios.setText("Precios");
        jMenuPrecios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPreciosMouseClicked(evt);
            }
        });
        jMenuPrecios.addActionListener(this::jMenuPreciosActionPerformed);
        jMenuBar2.add(jMenuPrecios);

        jMenuCarrito.setText("Carrito");
        jMenuCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCarritoMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenuCarrito);

        jMenuFacturas.setText("Facturas");
        jMenuFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuFacturasMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenuFacturas);

        jMenuEstado.setText("Estado");
        jMenuEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEstadoMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenuEstado);

        jMenuCompra.setText("Comprar");
        jMenuCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCompraMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenuCompra);

        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenuSalir);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPreciosActionPerformed
        
    }//GEN-LAST:event_jMenuPreciosActionPerformed

    private void jMenuPreciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPreciosMouseClicked
        // TODO add your handling code here:
        CombustiblePrecio precios = new CombustiblePrecio();
        precios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuPreciosMouseClicked

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCarritoMouseClicked
        // TODO add your handling code here:
        Carrito ct = new Carrito();
        ct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuCarritoMouseClicked

    private void jMenuEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEstadoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuEstadoMouseClicked

    private void jMenuFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuFacturasMouseClicked
        // TODO add your handling code here:
        facturacion fc = new facturacion();
        fc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuFacturasMouseClicked

    private void jMenuCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCompraMouseClicked
        // TODO add your handling code here:
        PantallaDePedido compras = new PantallaDePedido();
        compras.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jMenuCompraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuCarrito;
    private javax.swing.JMenu jMenuCompra;
    private javax.swing.JMenu jMenuEstado;
    private javax.swing.JMenu jMenuFacturas;
    private javax.swing.JMenu jMenuPrecios;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables

}
