/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DistribuidoraPetroPeru;

import java.util.List;

/**
 *
 * @author HP
 */

public class PasarelaPago extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PasarelaPago.class.getName());
    private Carrito pantallaCarrito;
    private java.util.List<Producto> listaCarrito;
    /**
     * Creates new form PasarelaPago
     */
    public PasarelaPago(Carrito pantallaCarrito, Object listaCarrito) {
        initComponents();
        this.pantallaCarrito = pantallaCarrito;
        this.listaCarrito = (List<Producto>) listaCarrito;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        NumTarjeta = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExpiracionDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Cvv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TitularTarjeta = new javax.swing.JTextField();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(NumTarjeta);

        jLabel1.setText("Numero de tarjeta:");

        jLabel2.setText("Fecha de expiracion:");

        ExpiracionDate.addActionListener(this::ExpiracionDateActionPerformed);

        jLabel3.setText("CVV");

        Cvv.addActionListener(this::CvvActionPerformed);

        jLabel4.setText("TITULAR");

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(this::btnPagarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(26, 26, 26))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TitularTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ExpiracionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(btnPagar)))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpiracionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TitularTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnPagar)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CvvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CvvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CvvActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        String numeroTarjeta = NumTarjeta.getText().replaceAll("\\s|-", ""); // Quita espacios o guiones si los hay
        String fechaExp = ExpiracionDate.getText().trim();
        String cvvStr = Cvv.getText().trim();
        String titular = TitularTarjeta.getText().trim();
        
        if (numeroTarjeta.isEmpty() || fechaExp.isEmpty() || cvvStr.isEmpty() || titular.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this,
                    "por favor complete todos los espacios.",
                    "Error: Complete todos los campos", 
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (validarAlgoritmoLuhn(numeroTarjeta)){
            javax.swing.JOptionPane.showMessageDialog(this, "Pago realizado con exito", 
            "Pago realizado",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );
            pantallaCarrito.finCompra();
            this.dispose();
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Tarjeta Invalida", 
            "Error en el metodo de pago", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
        }
//GEN-LAST:event_btnPagarActionPerformed

    private void ExpiracionDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpiracionDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpiracionDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    private boolean validarAlgoritmoLuhn(String numeroTarjeta){
        if (numeroTarjeta == null || numeroTarjeta.length()<13 || numeroTarjeta.length()>19){
            return false;
        }
        int suma = 0;
        boolean alternar = false;
        
        for(int i = numeroTarjeta.length() - 1; i >=0; i--){
            char c = numeroTarjeta.charAt(i);
            if(!Character.isDigit(c)){
                return false;
            }
            int n = Character.getNumericValue(c);
            if (alternar) {
                n *= 2;
                if (n > 9) {
                    n -=9;
                }
            }
            suma +=n;
            alternar = !alternar;
        }
        return (suma %10 == 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cvv;
    private javax.swing.JTextField ExpiracionDate;
    private javax.swing.JTextPane NumTarjeta;
    private javax.swing.JTextField TitularTarjeta;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
